-- The application accesses these tables through Prisma using the database
-- role. No table is accessed directly from the browser via Supabase REST.
-- Enabling RLS without anon/authenticated policies blocks accidental public
-- PostgREST access while preserving access for the database owner.

ALTER TABLE "addons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "admin_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "admin_users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "blogs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "cakes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "cake_variants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "comments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "customers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "customer_addresses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "dynamic_pages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "faqs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "flowers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "flower_images" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "flower_variants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "gallery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "gifts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "gift_variants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "global_pricing" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "homepage_circles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "homepage_sections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "homepage_section_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "homepage_slides" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "leads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "occasions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pricing_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "product_occasions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "promo_codes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "seo_meta" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "wishlist" ENABLE ROW LEVEL SECURITY;
